package constants

type Sprites int

const (
	UndefinedSprite = "undefined"
	Green           = "green"
	Yellow          = "yellow"
	Blue            = "blue"
	Purple          = "purple"
	Turquoise       = "turquoise"
	Brown           = "brown"
	Indigo          = "indigo"
	Red             = "red"
	Gold            = "gold"
	White           = "white"
	Orange          = "orange"
	Gray            = "gray"
	Apple           = "apple"
	Banana          = "banana"
	Leaks           = "leaks"
	GolfBalls       = "golf balls"
	GolfClub        = "golf club"
	GolfBag         = "golf bag"
	Vacuum          = "vacuum"
	Broom           = "broom"
	FrenchBread     = "french bread"
	Dustpan         = "dustpan"
	CrystalBall     = "crystal ball"
	JustARock       = "just a rock"
	SnakeOil        = "snake oil"
	TopHat          = "top hat"
	SteamerTrunk    = "steamer trunk"
	Encyclopedias   = "encyclopedias"
	FryingPan       = "frying pan"
	Dynamite        = "dynamite"
	Globe           = "globe"
	Whiskey         = "whiskey"
	Sarsaparilla    = "sarsaparilla"
	Shovel          = "shovel"
	Turtle          = "turtle"
	Rifle           = "rifle"
	Claranet        = "claranet"
	CowboyHat       = "cowboy hat"
	SmartTiny       = "smart_tiny"
	MiniTiny        = "mini_tiny"
	CargoTiny       = "cargo_tiny"
	BoxTiny         = "box_tiny"
	WagonTiny       = "wagon_tiny"
	MarketStandTiny = "marketstand_tiny"
)
